theme: jekyll-theme-minimal
plugins:
  - jekyll-remote-theme 
gems:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
title: Survey of "Best Paper" awards followup
description: Information about the project
